board/urls.py
from django.urls import path
from . import views

app_name = 'board'
urlpatterns = [
    path('', views.main, name='main'),
    path('<int:typeid>/excel_export', views.excel_export, name='excel_export'),
    path('<int:typeid>/excel_import', views.excel_import, name='excel_import'),

    path('code_index/', views.code_index, name='code_index'),
    path('code_add/', views.code_add, name='code_add'),
    path('code_add/code_add_exec', views.code_add_exec, name='code_add_exec'),
    path('code_index/<int:codeid>', views.code_detail, name='code_detail'),
    path('code_index/<int:codeid>/edit_code', views.edit_code, name='edit_code'),
    path('code_index/<int:codeid>/delete_code', views.delete_code, name='delete_code'),
    
    path('cluster_index/', views.cluster_index, name='cluster_index'),
    path('cluster_add/', views.cluster_add, name='cluster_add'),
    path('cluster_add/cluster_add_exec', views.cluster_add_exec, name='cluster_add_exec'),
    path('cluster_index/<int:clusterid>', views.cluster_detail, name='cluster_detail'),
    path('cluster_index/<int:clusterid>/edit_cluster', views.edit_cluster, name='edit_cluster'),
    path('cluster_index/<int:clusterid>/delete_cluster', views.delete_cluster, name='delete_cluster'),

    path('host_index/', views.host_index, name='host_index'),
    path('host_add/', views.host_add, name='host_add'),
    path('host_add/host_add_exec', views.host_add_exec, name='host_add_exec'),
    path('host_index/<int:hostid>', views.host_detail, name='host_detail'),
    path('host_index/<int:hostid>/host_edit', views.host_edit, name='host_edit'),
    path('host_index/<int:hostid>/delete_host', views.delete_host, name='delete_host'),

    path('storage_index/', views.storage_index, name='storage_index'),
    path('storage_add/', views.storage_add, name='storage_add'),
    path('storage_add/storage_add_exec', views.storage_add_exec, name='storage_add_exec'),
    path('storage_index/<int:storageid>', views.storage_detail, name='storage_detail'),
    path('storage_index/<int:storageid>/storage_edit', views.storage_edit, name='storage_edit'),
    path('storage_index/<int:storageid>/delete_storage', views.delete_storage, name='delete_storage'),

]

cloudweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('board.urls')),
    path('board/', include('board.urls')),
    path('admin/', admin.site.urls),
]

board/models.py
from django.db import models
import uuid

# Create your models here.
class CodeOption(models.Model):
    """
    CodeID : 코드ID
    CodeTypeID : 코드 타입 ID
    CodeTypeName : 코드 유형 명
    CodeDataID : 코드 데이터 ID
    CodeDataName : 코드 데이터 명
    CodeNote : 비고
    UseYN : 사용여부
    Created_data : 생성일자
    Modified_date : 수정일자
    """
    CodeID = models.AutoField(primary_key=True)
    CodeTypeID = models.CharField(max_length=3)
    CodeTypeName = models.CharField(max_length=100)
    CodeDataID = models.CharField(max_length=3)
    CodeDataName = models.CharField(max_length=100)
    CodeNote = models.CharField(max_length=100, null=True, blank=True)
    UseYN = models.CharField(max_length=1)
    Created_date = models.DateTimeField()
    Modified_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return str(self.CodeID)
    
class Cluster(models.Model):
    """
    ClusterID : 클러스터 ID
    ClusterName : 클러스터 명
    SERVER_TYPE1 : 영역 구분 1 (운영/개발/DR)
    SERVER_TYPE2 : 영역 구분 2 (중요/비중요)
    SERVER_TYPE3 : 영역 구분 3 (DMZ/AP/DB/LX/WIN/AP(W)/BIG/GPU/WLX)
    Created_data : 생성일자
    Modified_date : 수정일자
    """
    ClusterID = models.AutoField(primary_key=True)
    ClusterName = models.CharField(max_length=100)
    SERVER_TYPE1 = models.CharField(max_length=3)
    SERVER_TYPE2 = models.CharField(max_length=3)
    SERVER_TYPE3 = models.CharField(max_length=3)
    Created_date = models.DateTimeField()
    Modified_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return str(self.ClusterID)

class Host(models.Model):
    """
    HostID : 서버 ID
    HostName : 서버 명
    ClusterID : 서버 클러스터 ID
    Gen : 도입 세대
    Model : 서버 모델
    SerialNumber : 시리얼 번호
    CPU_Model : CPU 모델
    Core : CPU Core수
    Memory : 메모리 용량
    vSANDISK : 디스크 용량(vSAN 일경우)
    GPUMem : 메모리 용량(GPU 서버일 경우)
    EOS_Date : EOS 일자
    Created_Date : 생성 일자
    Modified_Date : 수정 일자
    """
    HostID = models.AutoField(primary_key=True)
    HostName = models.CharField(max_length=100)
    ClusterID = models.IntegerField()
    Gen = models.CharField(max_length=3)
    Model = models.CharField(max_length=100)
    SerialNumber = models.CharField(max_length=100)
    CPU_Model = models.CharField(max_length=100)
    Core = models.IntegerField()
    Memory = models.IntegerField()
    vSANDISK = models.IntegerField(null=True, blank=True)
    GPUMem = models.IntegerField(null=True, blank=True)
    EOS_Date = models.DateField(null=True, blank=True)
    Created_date = models.DateTimeField()
    Modified_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return str(self.HostID)

class Storage(models.Model):
    """
    StorageID : 스토리지 ID
    StorageName : 스토리지 명
    Gen : 도입 세대
    Model	 : 스토리지 모델
    SerialNumber : 시리얼 번호
    FuncType :기능 (SAN/NAS/SAN&NAS)
    Size : 스토리지 용량(GB)
    EOS_Date : EOS 일자
    Created_Date	 : 생성 일자
    Modified_Date : 수정 일자
    """
    StorageID = models.AutoField(primary_key=True)
    StorageName = models.CharField(max_length=100)
    Gen = models.CharField(max_length=3)
    Model = models.CharField(max_length=100)
    SerialNumber = models.CharField(max_length=100)
    FuncType = models.CharField(max_length=10)
    Size = models.IntegerField()
    EOS_Date = models.DateField(null=True, blank=True)
    Created_date = models.DateTimeField()
    Modified_date = models.DateTimeField(null=True, blank=True)

board/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.utils import timezone
from django.urls import reverse
from django.contrib import messages
from django.utils.timezone import make_aware
from datetime import datetime
import xlwt
import pandas as pd
from openpyxl import Workbook, load_workbook

from .models import CodeOption, Cluster, Host, Storage

# Main 페이지
def main(request):
    return render(request, 'board/main.html')

# Code 페이지
def code_index(request):
    #all_Codes = CodeOption.objects.all().order_by("-CodeTypeID", "-CodeDataID")
    #all_Codes = CodeOption.objects.filter(UseYN='Y').order_by("CodeTypeID", "CodeDataID")
    all_Codes = CodeOption.objects.all().order_by("CodeTypeID", "CodeDataID")
    return render(request, 'board/code_index.html', {'title': 'CODE 정보', 'board_list':all_Codes})

# Code 추가 페이지
def code_add(request):
    return render(request, 'board/code_add.html')

# Code 추가 처리
def code_add_exec(request):
    b = CodeOption(CodeTypeID=request.POST['CodeTypeID'], CodeTypeName=request.POST['CodeTypeName'], CodeDataID=request.POST['CodeDataID'], CodeDataName=request.POST['CodeDataName'], UseYN=request.POST['UseYN'], Created_date=timezone.now())
    b.save()
    return HttpResponseRedirect(reverse('board:code_index'))

# Code 상세 페이지
def code_detail(request, codeid):
    code = CodeOption.objects.get(CodeID=codeid)
    return render(request, 'board/code_detail.html', {'Code': code})

# Code 변경 처리 (Code_detail.html)
def edit_code(request, codeid):
    CodeOption.objects.filter(CodeID=codeid).update(CodeTypeID=request.POST['CodeTypeID'], CodeTypeName=request.POST['CodeTypeName'], CodeDataID=request.POST['CodeDataID']
                                                     , CodeDataName=request.POST['CodeDataName'], UseYN=request.POST['UseYN'], Modified_date=timezone.now())
    messages.add_message(request, messages.INFO, '변경되었습니다.')

    return redirect('/board/code_index/'+str(codeid))

# Code 삭제 처리 (Code_detail.html)
def delete_code(request, codeid):
    record = CodeOption.objects.get(CodeID=codeid)
    record.delete()

    return HttpResponseRedirect(reverse('board:code_index'))



# Cluster 페이지
def cluster_index(request):
    query = '''select A.ClusterID as 'ClusterID', A.ClusterName as 'ClusterName', B.CodeDataName as 'SERVER_TYPE1'
                                        ,C.CodeDataName as 'SERVER_TYPE2', D.CodeDataName as 'SERVER_TYPE3' 
                                        from board_cluster A
                                        left outer join (select * from board_codeoption where CodeTypeID = 'S01') B on A.SERVER_TYPE1 = B.CodeDataID
                                        left outer join (select * from board_codeoption where CodeTypeID = 'S02') C on A.SERVER_TYPE2 = C.CodeDataID
                                        left outer join (select * from board_codeoption where CodeTypeID = 'S03') D on A.SERVER_TYPE3 = D.CodeDataID
                                        order by B.CodeDataID, C.CodeDataID, D.CodeDataID, A.ClusterName
                                        '''
    all_Clusters = Cluster.objects.raw(query)
    return render(request, 'board/cluster_index.html', {'title': 'Cluster 정보', 'board_list':all_Clusters})

# Cluster 추가 페이지
def cluster_add(request):
    # 코드 정보에서 서버 타입 정보 조회 (도롭다운리스트에서 사용)
    type1 = CodeOption.objects.filter(CodeTypeID='S01').only('CodeDataID', 'CodeDataName')
    type2 = CodeOption.objects.filter(CodeTypeID='S02').only('CodeDataID', 'CodeDataName')
    type3 = CodeOption.objects.filter(CodeTypeID='S03').only('CodeDataID', 'CodeDataName')

    return render(request, 'board/cluster_add.html', {'type1_list':type1, 'type2_list':type2, 'type3_list':type3})

# cluster 추가 처리
def cluster_add_exec(request):
    b = Cluster(ClusterName=request.POST['ClusterName'], SERVER_TYPE1=request.POST['SERVER_TYPE1'], SERVER_TYPE2=request.POST['SERVER_TYPE2'], SERVER_TYPE3=request.POST['SERVER_TYPE3'], Created_date=timezone.now())
    b.save()
    return HttpResponseRedirect(reverse('board:cluster_index'))


# cluster 상세 페이지
def cluster_detail(request, clusterid):
    query = f'''select A.ClusterID as 'ClusterID', A.ClusterName as 'ClusterName' 
                    ,A.SERVER_TYPE1 as 'ST1_ID', B.CodeDataName as 'ST1_NAME'
                    ,A.SERVER_TYPE2 as 'ST2_ID', C.CodeDataName as 'ST2_NAME'
                    ,A.SERVER_TYPE2 as 'ST3_ID', D.CodeDataName as 'ST3_NAME'
                    ,A.Created_date as 'Created_date', A.Modified_date as 'Modified_date'
                from board_cluster A
                left outer join (select * from board_codeoption where CodeTypeID = 'S01') B on A.SERVER_TYPE1 = B.CodeDataID
                left outer join (select * from board_codeoption where CodeTypeID = 'S02') C on A.SERVER_TYPE2 = C.CodeDataID
                left outer join (select * from board_codeoption where CodeTypeID = 'S03') D on A.SERVER_TYPE3 = D.CodeDataID
                where A.ClusterID = {clusterid}'''
    cluster = Cluster.objects.raw(query)

    type1 = CodeOption.objects.filter(CodeTypeID='S01').only('CodeDataID', 'CodeDataName')
    type2 = CodeOption.objects.filter(CodeTypeID='S02').only('CodeDataID', 'CodeDataName')
    type3 = CodeOption.objects.filter(CodeTypeID='S03').only('CodeDataID', 'CodeDataName')

    return render(request, 'board/cluster_detail.html', {'cluster':cluster[0], 'type1_list':type1, 'type2_list':type2, 'type3_list':type3})


# cluster 변경 처리 (cluster_detail.html)
def edit_cluster(request, clusterid):
    Cluster.objects.filter(ClusterID=clusterid).update(ClusterName=request.POST['ClusterName'], SERVER_TYPE1=request.POST['SERVER_TYPE1'], SERVER_TYPE2=request.POST['SERVER_TYPE2'], SERVER_TYPE3=request.POST['SERVER_TYPE3'], Modified_date=timezone.now())
    messages.add_message(request, messages.INFO, '변경되었습니다.')

    return redirect('/board/cluster_index/'+str(clusterid))
    
# cluster 삭제 처리 (cluster_detail.html)
def delete_cluster(request, clusterid):
    record = Cluster.objects.get(ClusterID=clusterid)
    record.delete()

    return HttpResponseRedirect(reverse('board:cluster_index'))


# Host 페이지
def host_index(request):
    query = f'''select A.HostID as 'HostID', A.HostName as 'HostName', A.ClusterID as 'ClusterID', B.ClusterName as 'ClusterName'
                     ,A.Gen as 'GenID' ,B.CodeDataName as 'GenName', A.Model as 'Model', A.SerialNumber as 'SerialNumber'
                     ,A.CPU_Model as 'CPU_Model', A.Core as 'Core', A.Memory as 'Memory'
                     ,A.vSANDISK as 'vSANDISK', A.GPUMem as 'GPUMem', A.EOS_Date as 'EOS_Date'
                from board_host A
                left outer join board_cluster B on A.ClusterID = B.ClusterID
                left outer join (select * from board_codeoption where CodeTypeID = 'G01') B on A.Gen = B.CodeDataID
                order by A.HostName
            '''
    all_Hosts = Host.objects.raw(query)
    return render(request, 'board/host_index.html', {'title': 'Host 정보', 'board_list':all_Hosts})

# host 추가
def host_add(request):
    all_cluster = Cluster.objects.only('ClusterID', 'ClusterName')
    all_gen = CodeOption.objects.filter(CodeTypeID='G01').only('CodeDataID', 'CodeDataName')
    today = timezone.now()
    return render(request, 'board/host_add.html', {'cluster_list': all_cluster, 'gen_list': all_gen, 'today': today})

# host 추가 처리
def host_add_exec(request):
    b = Host(HostName=request.POST['HostName'], ClusterID=request.POST['ClusterID'], Gen=request.POST['Gen'], Model=request.POST['Model'], SerialNumber=request.POST['SerialNumber'], CPU_Model=request.POST['CPU_Model'], Core=request.POST['Core'], Memory=request.POST['Memory'], vSANDISK=nvl(request.POST['vSANDISK']), GPUMem=nvl(request.POST['GPUMem']), EOS_Date=request.POST['EOS_Date'], Created_date=timezone.now())
    b.save()
    return HttpResponseRedirect(reverse('board:host_index'))

# host 상세 페이지
def host_detail(request, hostid):
    query = f'''select A.HostID as 'HostID', A.HostName as 'HostName', A.ClusterID as 'ClusterID', B.ClusterName as 'ClusterName'
                     ,A.Gen as 'GenID' ,B.CodeDataName as 'GenName', A.Model as 'Model', A.SerialNumber as 'SerialNumber'
                     ,A.CPU_Model as 'CPU_Model', A.Core as 'Core', A.Memory as 'Memory'
                     ,A.vSANDISK as 'vSANDISK', A.GPUMem as 'GPUMem', A.EOS_Date as 'EOS_Date'
                from board_host A
                left outer join board_cluster B on A.ClusterID = B.ClusterID
                left outer join (select * from board_codeoption where CodeTypeID = 'G01') B on A.Gen = B.CodeDataID 
                where A.HostID = {hostid}
                order by A.HostName
            '''
    host = Cluster.objects.raw(query)

    all_cluster = Cluster.objects.only('ClusterID', 'ClusterName')
    all_gen = CodeOption.objects.filter(CodeTypeID='G01').only('CodeDataID', 'CodeDataName')

    return render(request, 'board/host_detail.html', {'host':host[0], 'cluster_list': all_cluster, 'gen_list': all_gen})

# Host 변경 처리 (host_detail.html)
def host_edit(request, hostid):
    Host.objects.filter(HostID=hostid).update(HostName=request.POST['HostName'], ClusterID=request.POST['ClusterID'], Gen=request.POST['Gen'], Model=request.POST['Model'], SerialNumber=request.POST['SerialNumber'], CPU_Model=request.POST['CPU_Model'], Core=request.POST['Core'], Memory=request.POST['Memory'], vSANDISK=nvl(request.POST['vSANDISK']), GPUMem=nvl(request.POST['GPUMem']), EOS_Date=request.POST['EOS_Date'], Modified_date=timezone.now())
    messages.add_message(request, messages.INFO, '변경되었습니다.')

    return redirect('/board/host_index/'+ str(hostid))

# host 삭제 처리 (host_detail.html)
def delete_host(request, hostid):
    record = Host.objects.get(HostID=hostid)
    record.delete()

    return HttpResponseRedirect(reverse('board:host_index'))


# Storage 페이지
def storage_index(request):
    query = f'''select A.StorageID as 'StorageID', A.StorageName as 'StorageName'

board/templates/board/cluster_index.html
{% include "./base.html" %}
<title>클러스터 정보</title>

{% block contents %}
<div class="cd1">
    <h1>클러스터 정보</h1>
    <div class="content">
        <div style="text-align:right;padding: 5px;">
            <button type="button" class="my_btn" onclick="location.href={% url 'board:cluster_add' %}">추가</button>
            <button type="button" class="btn-upload">업로드</button>
            <button type="button" class="my_btn">
                <a href="{% url 'board:excel_export' 1 %}">다운로드</a>
            </button>
        </div>
        {% if board_list %}
        <table class="board">
            <thead>
                <tr class="header">
                    <th style="width:10%;">ID</th>
                    <th style="width:30%">클러스터명</th>
                    <th style="width:20%">영역1</th>
                    <th style="width:20%">영역2</th>
                    <th style="width:20%">영역3</th>
                </tr>
            </thead>
            <tbody>
                {% for data in board_list %}
                <tr class="{% if forloop.counter|divisibleby:2 %}even_bgcolor{% endif %} code_tr" onClick=location.href="{% url 'board:cluster_detail' data.ClusterID %}" style="cursor:pointer;">
                    <td style="text-align:center;">{{ data.ClusterID }}</td>
                    <td style="text-align:center;">{{ data.ClusterName }}</td>
                    <td style="text-align:center;">{{ data.SERVER_TYPE1 }}</td>
                    <td style="text-align:center;">{{ data.SERVER_TYPE2 }}</td>
                    <td style="text-align:center;">{{ data.SERVER_TYPE3 }}</td>
                </tr>
                {% endfor %}
            
            </tbody>

        </table>
        {% else %}
            <tr>
                <td>등록된 클러스터가 없습니다.</td>
            </tr>
        {% endif %}


        <div class="modal">
            <div class="modal_body2">
                <label for="id_import_file" style="font-size:25px">클러스터 정보 Excel 데이터 업로드</label>
                <br>
                <p style="color:red">주의 : 기존 데이터에서 추가됩니다!</p>
                <br>
                <form action="{% url 'board:excel_import' 1 %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="file" name="excelFile" class="guess_format" accept=".xlsx;.xls">
                    <input type="submit" class="default" value="등록">
                </form>
                <br>
                <button type="button" class="btn-close-modal" id="close" style="ackground-color:skyblue;color:black;border:none;width: 70px;height:30px;">닫기</button>
            </div>
        </div>
    
        <script>
            const modal = document.querySelector('.modal');
            const btnOpenModal=document.querySelector('.btn-upload');
            const btnCloseModal=document.querySelector('.btn-close-modal');
    
            btnOpenModal.addEventListener("click", ()=>{
                modal.style.display="flex";
            });
            btnCloseModal.addEventListener("click", ()=>{
                modal.style.display="none";
            });
            
        </script>
    </div>
</div>
{% endblock %}

board/templates/board/code_index.html
{% include "./base.html" %}
<title>CODE 정보</title>

{% block contents %}
<div class="cd1">
    <h1>코드 정보</h1>
    <div class="content">
        <div style="text-align:right;padding: 5px;">
            <button type="button" class="my_btn" onclick="location.href={% url 'board:code_add' %}">추가</button>
            <button type="button" class="btn-upload">업로드</button>
            <button type="button" class="my_btn">
                <a href="{% url 'board:excel_export' 0 %}">다운로드</a>
            </button>
        </div>
        {% if board_list %}
        <table class="board">
            <thead>
                <tr class="header">
                    <th style="width:10%;">ID</th>
                    <th style="width:10%">TYPE ID</th>
                    <th style="width:25%">TYPE 명</th>
                    <th style="width:10%">DATA ID</th>
                    <th style="width:25%">DATA 명</th>
                    <th style="width:10%">사용여부</th>
                </tr>
            </thead>
            <tbody>
                {% for data in board_list %}
                <tr class="{% if forloop.counter|divisibleby:2 %}even_bgcolor{% endif %} code_tr" onClick=location.href="{% url 'board:code_detail' data.CodeID %}" style="cursor:pointer;">
                    <td style="text-align:center;">{{ data.CodeID }}</td>
                    <td style="text-align:center;">{{ data.CodeTypeID }}</td>
                    <td style="text-align:center;">{{ data.CodeTypeName }}</td>
                    <td style="text-align:center;">{{ data.CodeDataID }}</td>
                    <td style="text-align:center;">{{ data.CodeDataName }}</td>
                    <td style="text-align:center;">{{ data.UseYN }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <tr>
            <td>등록된 코드가 없습니다.</td>
        </tr>
        {% endif %}


        <div class="modal">
            <div class="modal_body2">
                <label for="id_import_file" style="font-size:25px">CODE 정보 Excel 데이터 업로드</label>
                <br>
                <p style="color:red">주의 : 기존 데이터에서 추가됩니다!</p>
                <br>
                <form action="{% url 'board:excel_import' 0 %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="file" name="excelFile" class="guess_format" accept=".xlsx;.xls">
                    <input type="submit" class="default" value="등록">
                </form>
                <br>
                <button type="button" class="btn-close-modal" id="close" style="ackground-color:skyblue;color:black;border:none;width: 70px;height:30px;">닫기</button>
            </div>
        </div>
    
        <script>
            const modal = document.querySelector('.modal');
            const btnOpenModal=document.querySelector('.btn-upload');
            const btnCloseModal=document.querySelector('.btn-close-modal');
    
            btnOpenModal.addEventListener("click", ()=>{
                modal.style.display="flex";
            });
            btnCloseModal.addEventListener("click", ()=>{
                modal.style.display="none";
            });
            
        </script>
    </div>
</div>
{% endblock %}

board/templates/board/host_index.html
{% include "./base.html" %}
<title>호스트 정보</title>

{% block contents %}
<div class="cd1">
    <h1>호스트 정보</h1>
    <div class="content">
        <div style="text-align:right;padding: 5px;">
            <button type="button" class="my_btn" onclick="location.href={% url 'board:host_add' %}">추가</button>
            <button type="button" class="btn-upload">업로드</button>
            <button type="button" class="my_btn">
                <a href="{% url 'board:excel_export' 2 %}">다운로드</a>
            </button>
        
        </div>
        {% if board_list %}
        <table class="board">
            <thead>
                <tr class="header">
                    <th style="width:2%;">ID</th>
                    <th style="width:15%">호스트명</th>
                    <th style="width:15%">클러스터</th>
                    <th style="width:5%">도입</th>
                    <th style="width:15%">모델</th>
                    <th style="width:10%">S/N</th>
                    <th style="width:15%">CPU</th>
                    <th style="width:2%">Core</th>
                    <th style="width:2%">Memory</th>
                    <th style="width:2%">vSAN</th>
                    <th style="width:2%">GPU</th>
                    <th style="width:10%">EOS</th>
                </tr>
            </thead>
            <tbody>
                {% for data in board_list %}
                <tr class="{% if forloop.counter|divisibleby:2 %}even_bgcolor{% endif %} code_tr" onClick=location.href="{% url 'board:host_detail' data.HostID %}" style="cursor:pointer;">
                    <td style="text-align:center;">{{ data.HostID }}</td>
                    <td style="text-align:center;">{{ data.HostName }}</td>
                    <td style="text-align:center;">{{ data.ClusterName }}</td>
                    <td style="text-align:center;">{{ data.GenName }}</td>
                    <td style="text-align:center;">{{ data.Model }}</td>
                    <td style="text-align:center;">{{ data.SerialNumber }}</td>
                    <td style="text-align:center;">{{ data.CPU_Model }}</td>
                    <td style="text-align:center;">{{ data.Core }}</td>
                    <td style="text-align:center;">{{ data.Memory }}</td>
                    <td style="text-align:center;">{{ data.vSANDISK }}</td>
                    <td style="text-align:center;">{{ data.GPUMem }}</td>
                    <td style="text-align:center;">{{ data.EOS_Date|date:'Y-m-d' }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <tr>
            <td>등록된 호스트가 없습니다.</td>
        </tr>
        {% endif %}

        <div class="modal">
            <div class="modal_body2">
                <label for="id_import_file" style="font-size:25px">호스트 정보 Excel 데이터 업로드</label>
                <br>
                <p style="color:red">주의 : 기존 데이터에서 추가됩니다!</p>
                <br>
                <form action="{% url 'board:excel_import' 2 %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="file" name="excelFile" class="guess_format" accept=".xlsx;.xls">
                    <input type="submit" class="default" value="등록">
                </form>
                <br>
                <button type="button" class="btn-close-modal" id="close" style="ackground-color:skyblue;color:black;border:none;width: 70px;height:30px;">닫기</button>
            </div>
        </div>
    
        <script>
            const modal = document.querySelector('.modal');
            const btnOpenModal=document.querySelector('.btn-upload');
            const btnCloseModal=document.querySelector('.btn-close-modal');
    
            btnOpenModal.addEventListener("click", ()=>{
                modal.style.display="flex";
            });
            btnCloseModal.addEventListener("click", ()=>{
                modal.style.display="none";
            });
            
        </script>

    </div>
</div>
{% endblock %}

board/templates/board/main.html
<!DOCTYPE html>
{% include "./base.html" %}

{% block contents %}
<div class="cd1">
    <h1>클라우드 관리 웹</h1>
    <h2>왼쪽 메뉴를 선택하시기 바랍니다.</h2>
    <br>
    <p>구성중...</p>
</div>
{% endblock %}